#!/usr/bin/env node

/**
 * Bilibili-BlackList - 构建脚本
 * 将模块化的代码打包成单个用户脚本文件
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 读取用户脚本头部
const scriptHeader = fs.readFileSync('./scripts/bilibili-blacklist.user.js', 'utf8');
const headerEndIndex = scriptHeader.indexOf('(function ()');
const header = scriptHeader.substring(0, headerEndIndex);

// 读取所有模块并合并
const modules = [
  './src/utils/helpers.js',
  './src/storage/manager.js',
  './src/core/blocker.js',
  './src/ui/manager.js',
  './src/adblock/main.js',
  './src/observers/page-observers.js',
  './src/main.js'
];

let combinedCode = header;

// 添加 IIFE 包装开始
combinedCode += '\n(function () {\n  "use strict";\n\n';

// 添加注释分隔
combinedCode += '  /* ================ 工具函数模块 ================ */\n';
const utilsCode = fs.readFileSync(modules[0], 'utf8');
// 移除import/export语句，将其转换为函数定义
combinedCode += utilsCode
  .replace(/export\s+function\s+/g, '  function ')
  .replace(/export\s+{([^}]+)}/g, '') // 移除export { ... }
  .replace(/import\s+{([^}]+)}\s+from\s+['"][^'"]+['"]\s*/g, '') // 移除import语句
  .replace(/export\s+class\s+/g, '  class ');

// 添加注释分隔
combinedCode += '\n  /* ================ 存储管理模块 ================ */\n';
const storageCode = fs.readFileSync(modules[1], 'utf8');
combinedCode += storageCode
  .replace(/export\s+class\s+/g, '  class ')
  .replace(/import\s+{([^}]+)}\s+from\s+['"][^'"]+['"]\s*/g, '');

// 添加注释分隔
combinedCode += '\n  /* ================ 核心屏蔽模块 ================ */\n';
const coreCode = fs.readFileSync(modules[2], 'utf8');
combinedCode += coreCode
  .replace(/import\s+{([^}]+)}\s+from\s+['"][^'"]+['"]\s*/g, '')
  .replace(/export\s+class\s+/g, '  class ');

// 添加注释分隔
combinedCode += '\n  /* ================ UI管理模块 ================ */\n';
const uiCode = fs.readFileSync(modules[3], 'utf8');
combinedCode += uiCode
  .replace(/import\s+{([^}]+)}\s+from\s+['"][^'"]+['"]\s*/g, '')
  .replace(/export\s+class\s+/g, '  class ');

// 添加注释分隔
combinedCode += '\n  /* ================ 广告屏蔽模块 ================ */\n';
const adblockCode = fs.readFileSync(modules[4], 'utf8');
combinedCode += adblockCode
  .replace(/import\s+{([^}]+)}\s+from\s+['"][^'"]+['"]\s*/g, '')
  .replace(/export\s+class\s+/g, '  class ');

// 添加注释分隔
combinedCode += '\n  /* ================ 页面观察器模块 ================ */\n';
const observersCode = fs.readFileSync(modules[5], 'utf8');
combinedCode += observersCode
  .replace(/import\s+{([^}]+)}\s+from\s+['"][^'"]+['"]\s*/g, '')
  .replace(/export\s+class\s+/g, '  class ');

// 添加注释分隔
combinedCode += '\n  /* ================ 主入口模块 ================ */\n';
const mainCode = fs.readFileSync(modules[6], 'utf8');
combinedCode += mainCode
  .replace(/import\s+{([^}]+)}\s+from\s+['"][^'"]+['"]\s*/g, '')
  .replace(/export\s+{([^}]+)}/g, ''); // 移除export语句

// 添加 IIFE 包装结束
combinedCode += '\n  /*\n   * Bilibili-BlackList -- Bilibili UP屏蔽插件\n   * 重构版本 - 模块化设计，提高可维护性和可读性\n   * this script is mainly generated by AI, the author doesn\'t know JavaScript at all, if there are bugs, please contact Gemini / ChatGPT / DeepSeek\n   * 感谢你的使用\n   * Thank you for using this script\n   */\n\n  // 初始化所有模块\n  const storageManager = new StorageManager();\n  const config = storageManager.getGlobalConfig();\n  const blocker = new CoreBlocker(storageManager, config);\n  const uiManager = new UIManager(storageManager, blocker);\n  const pageObserver = new PageObserver(blocker, uiManager, storageManager);\n  const adBlocker = new AdBlocker(storageManager, blocker);\n\n  // 添加全局样式\n  uiManager.addGlobalStyles();\n\n  // 设置页面可见性监听器\n  pageObserver.setupPageVisibilityListener();\n\n  // 监听DOMContentLoaded并检查readyState以进行早期初始化\n  document.addEventListener("DOMContentLoaded", () => {\n    pageObserver.initializeObserver();\n  });\n  \n  if (\n    document.readyState === "complete" ||\n    document.readyState === "interactive"\n  ) {\n    pageObserver.initializeObserver();\n  }\n\n  // 暴露一些功能到全局，方便调试\n  window.BilibiliBlackList = {\n    storageManager,\n    blocker,\n    uiManager,\n    pageObserver,\n    adBlocker,\n    refreshUI: () => {\n      uiManager.refreshAllPanelTabs();\n      uiManager.refreshBlockCountDisplay();\n    }\n  };\n\n  console.log("[bilibili-blacklist] 重构版本已加载，模块化设计 🚀");\n\n})();';

// 写入构建后的文件
fs.writeFileSync('./dist/bilibili-blacklist.user.js', combinedCode);
console.log('构建完成！生成的文件: ./dist/bilibili-blacklist.user.js');