/**
 * Bilibili-BlackList - 主入口文件
 * 整合所有模块并初始化脚本
 */

import { StorageManager } from './storage/manager.js';
import { CoreBlocker } from './core/blocker.js';
import { UIManager } from './ui/manager.js';
import { PageObserver } from './observers/page-observers.js';
import { AdBlocker } from './adblock/main.js';

(function () {
  "use strict";

  /*
   * Bilibili-BlackList -- Bilibili UP屏蔽插件
   * 重构版本 - 模块化设计，提高可维护性和可读性
   * 代码已由 QWEN Coder 重构为模块化结构
   * this script is mainly generated by AI, the author doesn't know JavaScript at all, if there are bugs, please contact Gemini / ChatGPT / DeepSeek
   * 感谢你的使用
   * Thank you for using this script
   */

  // 初始化所有模块
  const storageManager = new StorageManager();
  const config = storageManager.getGlobalConfig();
  const blocker = new CoreBlocker(storageManager, config);
  const uiManager = new UIManager(storageManager, blocker);
  const pageObserver = new PageObserver(blocker, uiManager, storageManager);
  const adBlocker = new AdBlocker(storageManager, blocker);

  // 添加全局样式
  uiManager.addGlobalStyles();

  // 设置页面可见性监听器
  pageObserver.setupPageVisibilityListener();

  // 监听DOMContentLoaded并检查readyState以进行早期初始化
  document.addEventListener("DOMContentLoaded", () => {
    pageObserver.initializeObserver();
  });
  
  if (
    document.readyState === "complete" ||
    document.readyState === "interactive"
  ) {
    pageObserver.initializeObserver();
  }

  // 暴露一些功能到全局，方便调试
  window.BilibiliBlackList = {
    storageManager,
    blocker,
    uiManager,
    pageObserver,
    adBlocker,
    refreshUI: () => {
      uiManager.refreshAllPanelTabs();
      uiManager.refreshBlockCountDisplay();
    }
  };

  console.log("[bilibili-blacklist] 重构版本已加载，模块化设计 🚀");
})();